In [28]:
from shapely.ops import nearest_points, unary_union
from shapely.geometry import Polygon, LineString, Point
triangle = Polygon([(0, 0), (1, 0), (0.5, 1), (0, 0)])
square = Polygon([(0, 2), (1, 2), (1, 3), (0, 3), (0, 2)])
[o.wkt for o in nearest_points(triangle, square)]
#['POINT (0.5 1)', 'POINT (0.5 2)']

['POINT (0.5 1)', 'POINT (0.5 2)']

In [8]:
unary_union([triangle, square] + list(nearest_points(triangle, square)))

In [10]:
import pandas as pd

In [14]:
series = pd.Series(["abc", "cdf"])

In [18]:
for ser in series.items():
    print(ser)

(0, 'abc')
(1, 'cdf')

In [21]:
line = LineString([(0,1), (1,0)])

In [36]:
a, b = line.coords

In [38]:
b

(1.0, 0.0)

In [51]:
round(1.1, 1)

1.1

In [39]:
from shapely.ops import snap

In [48]:
snap(Point(.9,0), LineString([(1,0), (0,1)]), 3).coords[0]

(0.0, 1.0)

In [54]:
line.coords[0]

(0.0, 1.0)

In [55]:
tuple(line.coords)

((0.0, 1.0), (1.0, 0.0))

In [58]:
Point(1,0).coords[0]

(1.0, 0.0)

In [60]:
import pandas as pd
us_cities = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/us-cities-top-1k.csv")

In [61]:
us_cities

                    City           State  Population        lat         lon
0             Marysville      Washington       63269  48.051764 -122.177082
1                 Perris      California       72326  33.782519 -117.228648
2              Cleveland            Ohio      390113  41.499320  -81.694361
3              Worcester   Massachusetts      182544  42.262593  -71.802293
4               Columbia  South Carolina      133358  34.000710  -81.034814
5              Waterbury     Connecticut      109676  41.558153  -73.051496
6                  Eagan       Minnesota       65453  44.804132  -93.166886
7             Southfield        Michigan       73006  42.473369  -83.221873
8              Lafayette       Louisiana      124276  30.224090  -92.019843
9             Boise City           Idaho      214237  43.618710 -116.214607
10               Elkhart         Indiana       51265  41.681993  -85.976667
11            Buena Park      California       82882  33.867514 -117.998118
12              Marietta         Georgia       59089  33.952602  -84.549933
13                Parker        Colorado       48608  39.518600 -104.761363
14       West Palm Beach         Florida      102436  26.715342  -80.053375
15                 Salem   Massachusetts       42544  42.519540  -70.896715
16                Aurora        Illinois      199963  41.760585  -88.320071
17              Leesburg        Virginia       47673  39.115662  -77.563602
18                 Doral         Florida       50213  25.819542  -80.355330
19           Westminster      California       91739  33.751342 -117.993992
20               Lubbock           Texas      239538  33.577863 -101.855166
21         Overland Park          Kansas      181260  38.982228  -94.670792
22               Jackson     Mississippi      172638  32.298757  -90.184810
23              Gastonia  North Carolina       73209  35.262082  -81.187301
24         Daytona Beach         Florida       62316  29.210815  -81.022833
25           Kansas City        Missouri      467007  39.099727  -94.578567
26   Rancho Palos Verdes      California       42448  33.744461 -118.387017
27            Burnsville       Minnesota       61434  44.767742  -93.277723
28               Rowlett           Texas       58043  32.902902  -96.563880
29               Roswell      New Mexico       48611  33.394266 -104.523024
..                   ...             ...         ...        ...         ...
970                Ocala         Florida       57468  29.187199  -82.140092
971              Roswell         Georgia       94034  34.023243  -84.361556
972           Park Ridge        Illinois       37839  42.011141  -87.840619
973              Concord   New Hampshire       42419  43.208137  -71.537572
974              Olympia      Washington       48338  47.037874 -122.900695
975     Huntington Beach      California      197575  33.660297 -117.999227
976       Corpus Christi           Texas      316381  27.800583  -97.396381
977            Haverhill   Massachusetts       62088  42.776201  -71.077280
978         Hanover Park        Illinois       38510  41.999472  -88.145073
979            Cambridge   Massachusetts      107289  42.373616  -71.109733
980             Glendale         Arizona      234632  33.538652 -112.185987
981              Stanton      California       38623  33.802516 -117.993116
982          Summerville  South Carolina       46074  33.018504  -80.175648
983            Davenport            Iowa      102157  41.523644  -90.577637
984           Boca Raton         Florida       89407  26.368306  -80.128932
985          New Britain     Connecticut       72939  41.661210  -72.779542
986            Roseville        Michigan       47555  42.497258  -82.937141
987    Cleveland Heights            Ohio       45394  41.520052  -81.556235
988              Gresham          Oregon      109397  45.500136 -122.430201
989           Lauderhill         Florida       69813  26.140363  -80.213381
990       Hendersonville       Tennessee       54068  36.304774  -86.619996
991          Santa Clara      California      120245  37.354108 -121.955236
992            Oceanside      California      172794  33.195870 -117.379483
993          Lake Forest      California       79312  33.646966 -117.689218
994                 Novi        Michigan       57960  42.480590  -83.475491
995        West New York      New Jersey       52122  40.787879  -74.014306
996              Everett   Massachusetts       42935  42.408430  -71.053663
997               Linden      New Jersey       41301  40.622048  -74.244590
998            Asheville  North Carolina       87236  35.595058  -82.551487
999              Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]